# Generated by Django 5.0 on 2024-01-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('traduccion', models.CharField(max_length=60)),
                ('año', models.IntegerField()),
                ('caps', models.IntegerField()),
                ('creador', models.CharField(max_length=60)),
                ('site', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('traduccion', models.CharField(max_length=60)),
                ('año', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('creador', models.CharField(max_length=60)),
                ('site', models.CharField(max_length=60)),
            ],
        ),
    ]
