# Generated by Django 5.0 on 2024-01-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnime', '0002_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('traduccion', models.CharField(max_length=60)),
                ('año', models.IntegerField()),
                ('plataforma', models.CharField(max_length=60)),
                ('creador', models.CharField(max_length=60)),
            ],
        ),
    ]
